### PR TITLE
Fix structure created by resource-download

### LINKED ISSUE #56: resource-download creates wrong structure locally
Since #45 the downloaded files ended up in a struture like this:

```
Data/Persistent/Resources
├── 0
│   ├── 1
│   │   ├── 0
│   │   │   └── 1010152dbf465371a9329a34c1a2cf6b31427b352
│   │   │       └── All tests configuration-250x153.png
│   │   └── 5
│   │       └── 50155f33907e1dedca6892ee7184559df22e4612f
│   │           └── IMG_20140329_175546-1000x291.jpg
```

But this would be correct:

```
Data/Persistent/Resources
├── 0
│   ├── 1
│   │   ├── 0
│   │   │   └── 1
│   │   │       └── 010152dbf465371a9329a34c1a2cf6b31427b352
│   │   └── 5
│   │       └── 5
│   │           └── 0155f33907e1dedca6892ee7184559df22e4612f
```

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #56

### CODE REVIEW

File: cmd/beach/cmd/resource-download.go [hunk 1]
```diff
@@ -98,15 +98,15 @@ func handleResourceDownloadRun(cmd *cobra.Command, args []string) {
...
+			targetPath := filepath.Dir(sandbox.ProjectDataPersistentResourcesPath + "/" + getRelativePersistentResourcePathByHash(attributes.Name) + "/")
 
 			err = os.MkdirAll(targetPath, 0755)
 			if err != nil {
 				log.Fatal(err)
 				return
 			}
 
-			file, err := os.OpenFile(targetPath+"/"+filepath.Base(attributes.Name), os.O_RDWR|os.O_CREATE, 0644)
+			file, err := os.OpenFile(targetPath+"/"+filepath.Dir(attributes.Name), os.O_RDWR|os.O_CREATE, 0644)
```
Comment (kitsunet) [inline cmd/beach/cmd/resource-download.go:109]: this works reliably? I guess as long as we don't change how we store them in the cloud storage...

**Review by kitsunet — APPROVED** [review]

File: cmd/beach/cmd/resource-download.go (hunk 1 above)
Comment (kdambekalns) [reply cmd/beach/cmd/resource-download.go:109]: … and I can't think of a reason for changing it. 😎
